# Aula 30/02/2025

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
base = pd.read_csv("https://raw.githubusercontent.com/andfranca/proadi-sus-ciencia-de-dados-ia/refs/heads/main/bases/banco-laboratorio.csv")

In [4]:
base

,IDCOLABORADOR,IDADE,INSATISTFEITO,STATUSCIVIL,GENERO,NOME,SETOR,CARGO,CEP,NIVELEDUCACAO,FORMACAO,RENDAMENSAL,DESCONTOULTIMAFATURA,ANONAEMPRESA,ANOSMESMAPOSICAO,ANOSDESDEULTIMAPROMOCAO
0,1,41,Sim,Solteiro,Feminino,Maria da Silva,Alimentos,Auditor,1.0,2,Ciencias Sociais,19479,Sim,6,4,0
1,5,33,Nao,Casado,Feminino,Ana Oliveira,Saude,Pesquisador,3.0,4,Ciencias Sociais,23159,Sim,8,7,3
2,10,59,Nao,Casado,Feminino,Juliana Santos,Saude,Tecnico de Laboratorio,3.0,3,Medicina,9964,Sim,1,0,0
3,15,29,Nao,Solteiro,Feminino,Fernanda Costa,Saude,Tecnico de Laboratorio,NaN,2,Ciencias Sociais,12682,Sim,9,5,0
4,20,29,Nao,Divorciado,Feminino,Beatriz Lima,Saude,Diretor de Manufatura,21.0,4,Ciencias Sociais,10195,Nao,10,9,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,2061,36,Nao,Casado,Masculino,Otavio Dias,Saude,Tecnico de Laboratorio,23.0,2,Medicina,12290,Nao,5,2,0
1466,2062,39,Nao,Casado,Masculino,Pedro Barros,Saude,Representante da Saude,6.0,1,Medicina,21457,Nao,7,7,1
1467,2064,27,Nao,Casado,Masculino,Ravi Santos,Saude,Diretor de Manufatura,4.0,3,Ciencias Sociais,5174,Sim,6,2,0
1468,2065,49,Nao,Casado,Masculino,Theo Costa,Alimentos,Auditor,2.0,3,Medicina,13243,Nao,9,6,0
1469,2068,34,Nao,Casado,Masculino,Eduardo Mendes,Saude,Tecnico de Laboratorio,NaN,3,Medicina,10228,Nao,4,3,1

In [5]:
base.describe()

,IDCOLABORADOR,IDADE,CEP,NIVELEDUCACAO,RENDAMENSAL,ANONAEMPRESA,ANOSMESMAPOSICAO,ANOSDESDEULTIMAPROMOCAO
count,1470.000000,1470.000000,1426.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,1024.865306,36.923810,9.140252,2.912925,14313.103401,7.008163,4.229252,2.187755
std,602.024335,9.135373,8.065954,1.024165,7117.786044,6.126525,3.623137,3.222430
min,1.000000,18.000000,1.000000,1.000000,2094.000000,0.000000,0.000000,0.000000
25%,491.250000,30.000000,2.000000,2.000000,8047.000000,3.000000,2.000000,0.000000
50%,1020.500000,36.000000,7.000000,3.000000,14235.500000,5.000000,3.000000,1.000000
75%,1555.750000,43.000000,14.000000,4.000000,20461.500000,9.000000,7.000000,3.000000
max,2068.000000,60.000000,29.000000,5.000000,26999.000000,40.000000,18.000000,15.000000

In [6]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   IDCOLABORADOR            1470 non-null   int64
 1   IDADE                    1470 non-null   int64
 2   INSATISTFEITO            1470 non-null   object
 3   STATUSCIVIL              1470 non-null   object
 4   GENERO                   1470 non-null   object
 5   NOME                     1470 non-null   object
 6   SETOR                    1470 non-null   object
 7   CARGO                    1470 non-null   object
 8   CEP                      1426 non-null   float64
 9   NIVELEDUCACAO            1470 non-null   int64
 10  FORMACAO                 1470 non-null   object
 11  RENDAMENSAL              1470 non-null   int64
 12  DESCONTOULTIMAFATURA     1470 non-null   object
 13  ANONAEMPRESA             1470 non-null   int64
 14  ANOSMESMAPOSICAO         1470 non-null   int64
 15  ANOSDESDEULTIMAPROMOCAO  1470 non-null   int64
dtypes: float64(1), int64(7), object(8)
memory usage: 183.9+ KB

In [7]:
base.isna().sum()

IDCOLABORADOR               0
IDADE                       0
INSATISTFEITO               0
STATUSCIVIL                 0
GENERO                      0
NOME                        0
SETOR                       0
CARGO                       0
CEP                        44
NIVELEDUCACAO               0
FORMACAO                    0
RENDAMENSAL                 0
DESCONTOULTIMAFATURA        0
ANONAEMPRESA                0
ANOSMESMAPOSICAO            0
ANOSDESDEULTIMAPROMOCAO     0
dtype: int64

In [8]:
base[['IDADE','INSATISTFEITO']]

      IDADE INSATISTFEITO
0        41           Sim
1        33           Nao
2        59           Nao
3        29           Nao
4        29           Nao
...     ...           ...
1465     36           Nao
1466     39           Nao
1467     27           Nao
1468     49           Nao
1469     34           Nao

[1470 rows x 2 columns]

In [9]:
base[base['IDADE']>=30]

,IDCOLABORADOR,IDADE,INSATISTFEITO,STATUSCIVIL,GENERO,NOME,SETOR,CARGO,CEP,NIVELEDUCACAO,FORMACAO,RENDAMENSAL,DESCONTOULTIMAFATURA,ANONAEMPRESA,ANOSMESMAPOSICAO,ANOSDESDEULTIMAPROMOCAO
0,1,41,Sim,Solteiro,Feminino,Maria da Silva,Alimentos,Auditor,1.0,2,Ciencias Sociais,19479,Sim,6,4,0
1,5,33,Nao,Casado,Feminino,Ana Oliveira,Saude,Pesquisador,3.0,4,Ciencias Sociais,23159,Sim,8,7,3
2,10,59,Nao,Casado,Feminino,Juliana Santos,Saude,Tecnico de Laboratorio,3.0,3,Medicina,9964,Sim,1,0,0
5,23,53,Nao,Casado,Feminino,Adriana Pereira,Alimentos,Gestor,2.0,4,Ciencias Sociais,22021,Nao,25,8,3
7,28,34,Nao,Solteiro,Feminino,Camila Fernandes,Saude,Diretor de Pesquisa,7.0,4,Ciencias Sociais,21293,Nao,12,6,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,2057,31,Nao,Solteiro,Masculino,Nicolas Teixeira,Saude,Diretor de Manufatura,5.0,3,Medicina,3787,Nao,9,4,1
1465,2061,36,Nao,Casado,Masculino,Otavio Dias,Saude,Tecnico de Laboratorio,23.0,2,Medicina,12290,Nao,5,2,0
1466,2062,39,Nao,Casado,Masculino,Pedro Barros,Saude,Representante da Saude,6.0,1,Medicina,21457,Nao,7,7,1
1468,2065,49,Nao,Casado,Masculino,Theo Costa,Alimentos,Auditor,2.0,3,Medicina,13243,Nao,9,6,0
1469,2068,34,Nao,Casado,Masculino,Eduardo Mendes,Saude,Tecnico de Laboratorio,NaN,3,Medicina,10228,Nao,4,3,1

In [10]:
base[
    (base['IDADE']>=30)&
    (base['STATUSCIVIL']=='Casado')
    ]

,IDCOLABORADOR,IDADE,INSATISTFEITO,STATUSCIVIL,GENERO,NOME,SETOR,CARGO,CEP,NIVELEDUCACAO,FORMACAO,RENDAMENSAL,DESCONTOULTIMAFATURA,ANONAEMPRESA,ANOSMESMAPOSICAO,ANOSDESDEULTIMAPROMOCAO
1,5,33,Nao,Casado,Feminino,Ana Oliveira,Saude,Pesquisador,3.0,4,Ciencias Sociais,23159,Sim,8,7,3
2,10,59,Nao,Casado,Feminino,Juliana Santos,Saude,Tecnico de Laboratorio,3.0,3,Medicina,9964,Sim,1,0,0
5,23,53,Nao,Casado,Feminino,Adriana Pereira,Alimentos,Gestor,2.0,4,Ciencias Sociais,22021,Nao,25,8,3
10,36,44,Nao,Casado,Feminino,Vanessa Souza,Saude,Representante da Saude,7.0,4,Medicina,2094,Nao,22,6,5
13,49,35,Nao,Casado,Feminino,Isabela Oliveira,Alimentos,Representante de Setor,2.0,3,Marketing,9687,Nao,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1461,2049,35,Nao,Casado,Masculino,Joao Ferreira,Saude,Representante da Saude,18.0,4,Ciencias Sociais,24594,Sim,10,2,0
1465,2061,36,Nao,Casado,Masculino,Otavio Dias,Saude,Tecnico de Laboratorio,23.0,2,Medicina,12290,Nao,5,2,0
1466,2062,39,Nao,Casado,Masculino,Pedro Barros,Saude,Representante da Saude,6.0,1,Medicina,21457,Nao,7,7,1
1468,2065,49,Nao,Casado,Masculino,Theo Costa,Alimentos,Auditor,2.0,3,Medicina,13243,Nao,9,6,0
1469,2068,34,Nao,Casado,Masculino,Eduardo Mendes,Saude,Tecnico de Laboratorio,NaN,3,Medicina,10228,Nao,4,3,1

#Aplicando filtros

In [11]:
base[
    (base['IDADE']>=30)&
    (base['STATUSCIVIL']=='Casado')&
    (base['INSATISTFEITO']=="Sim")
    ]

,IDCOLABORADOR,IDADE,INSATISTFEITO,STATUSCIVIL,GENERO,NOME,SETOR,CARGO,CEP,NIVELEDUCACAO,FORMACAO,RENDAMENSAL,DESCONTOULTIMAFATURA,ANONAEMPRESA,ANOSMESMAPOSICAO,ANOSDESDEULTIMAPROMOCAO
18,58,41,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Pesquisa,12.0,3,Formacao Tecnica,16280,Nao,22,15,15
46,161,56,Sim,Casado,Feminino,Vanessa Carvalho,Saude,Pesquisador,14.0,4,Ciencias Sociais,4510,Sim,5,4,4
48,165,58,Sim,Casado,Feminino,Amanda Goncalves,Saude,Representante da Saude,23.0,4,Medicina,3465,Nao,40,10,15
52,175,31,Sim,Casado,Feminino,Ana Pereira,Alimentos,Auditor,20.0,3,Ciencias Sociais,24788,Sim,2,2,2
96,328,33,Sim,Casado,Feminino,Patricia Oliveira,Saude,Tecnico de Laboratorio,2.0,2,Ciencias Sociais,21509,Nao,9,7,1
126,445,39,Sim,Casado,Feminino,Tatiane Carvalho,Alimentos,Auditor,3.0,2,Medicina,17778,Sim,1,0,0
203,684,45,Sim,Casado,Feminino,Fernanda Costa,Alimentos,Auditor,26.0,4,Ciencias Sociais,5630,Nao,1,1,0
247,840,49,Sim,Casado,Feminino,Bruna Almeida,Alimentos,Auditor,11.0,3,Marketing,5860,Nao,9,8,7
294,1004,30,Sim,Casado,Feminino,Laura Pereira,Saude,Pesquisador,22.0,3,Ciencias Sociais,11539,Sim,5,2,0
306,1033,37,Sim,Casado,Feminino,Leticia Oliveira,Saude,Representante da Saude,11.0,2,Medicina,14382,Nao,1,0,0
308,1038,52,Sim,Casado,Feminino,Valentina Martins,Alimentos,Gestor,2.0,1,Marketing,25846,Nao,32,14,6
380,1295,44,Sim,Casado,Feminino,Fernanda Alves,Saude,Representante da Saude,15.0,3,Medicina,14075,Nao,10,7,0
399,1360,58,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Manufatura,7.0,4,Medicina,12023,Sim,10,9,5
408,1380,35,Sim,Casado,Feminino,Daniela Silva,Alimentos,Auditor,18.0,4,Marketing,23288,Sim,4,2,3
434,1467,34,Sim,Casado,Feminino,Luana Almeida,Medicamentos,Tecnico de TI,9.0,4,Formacao Tecnica,3072,Nao,2,2,2
454,1572,53,Sim,Casado,Feminino,Rafaela Santos,Saude,Diretor de Manufatura,2.0,5,Formacao Tecnica,14618,Nao,33,7,1
494,1691,48,Sim,Casado,Feminino,Michele Almeida,Alimentos,Representante de Setor,7.0,2,Medicina,11740,Sim,9,7,7
523,1821,46,Sim,Casado,Feminino,Luana Oliveira,Saude,Representante da Saude,21.0,2,Medicina,10842,Nao,9,7,3
539,1869,46,Sim,Casado,Feminino,Priscila Pereira,Alimentos,Auditor,10.0,3,Ciencias Sociais,14011,Nao,8,7,0
609,42,39,Sim,Casado,Masculino,Anselmo Souza,Alimentos,Representante de Setor,NaN,3,Formacao Tecnica,3335,Nao,1,0,0
611,47,50,Sim,Casado,Masculino,AntÃ´nio Oliveira,Alimentos,Representante de Setor,3.0,2,Marketing,3810,Sim,3,2,0
629,90,36,Sim,Casado,Masculino,Cicero Dias,Saude,Pesquisador,9.0,3,Medicina,21777,Sim,1,0,0
665,163,31,Sim,Casado,Masculino,Genaro Rodrigues,Alimentos,Auditor,6.0,4,Ciencias Sociais,20739,Sim,7,7,7
700,261,35,Sim,Casado,Masculino,Marinheiro Dias,Saude,Diretor de Manufatura,23.0,2,Ciencias Sociais,15497,Sim,1,0,0
710,282,38,Sim,Casado,Masculino,Nathan Nunes,Saude,Representante da Saude,29.0,1,Medicina,11354,Sim,1,0,0
714,291,32,Sim,Casado,Masculino,Olavo Costa,Alimentos,Auditor,4.0,4,Medicina,25812,Nao,14,8,9
727,325,33,Sim,Casado,Masculino,Ranieri Nunes,Saude,Tecnico de Laboratorio,14.0,3,Medicina,22149,Sim,5,4,0
753,376,47,Sim,Casado,Masculino,Victor Barros,Saude,Gestor,29.0,4,Ciencias Sociais,10268,Sim,10,7,9
784,433,52,Sim,Casado,Masculino,Bernardo Jose Ferreira,Saude,Pesquisador,8.0,4,Medicina,17747,Nao,8,2,7
812,492,40,Sim,Casado,Masculino,Edmilson Costa,Alimentos,Auditor,22.0,2,Marketing,6110,Sim,6,4,1
845,582,33,Sim,Casado,Masculino,Joaquim Nunes,Saude,Gestor,15.0,1,Medicina,24619,Sim,7,6,7
849,587,31,Sim,Casado,Masculino,Jose Roberto Barros,Saude,Representante da Saude,20.0,3,Ciencias Sociais,22908,Nao,1,0,0
867,631,32,Sim,Casado,Masculino,Enzo Nunes,Alimentos,Auditor,11.0,4,Outros,23914,Nao,4,2,1
875,648,30,Sim,Casado,Masculino,Gael Rodrigues,Alimentos,Representante de Setor,12.0,4,Ciencias Sociais,14470,Nao,1,0,0
905,723,50,Sim,Casado,Masculino,Gael Rodrigues,Alimentos,Auditor,8.0,2,Formacao Tecnica,23452,Sim,4,3,1
930,787,55,Sim,Casado,Masculino,Gael Barros,Saude,Gestor,2.0,3,Medicina,21199,Sim,5,2,1
984,932,39,Sim,Casado,Masculino,Gael Nunes,Saude,Tecnico de Laboratorio,6.0,3,Medicina,4303,Sim,2,2,2
998,967,36,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,3.0,1,Ciencias Sociais,5518,Sim,16,7,3
999,970,37,Sim,Casado,Masculino,Otavio Dias,Alimentos,Auditor,1.0,4,Ciencias Sociais,14922,Nao,14,1,11
1041,1081,51,Sim,Casado,Masculino,Miguel Martins,Saude,Pesquisador,4.0,4,Ciencias Sociais,10332,Sim,10,0,2
1048,1098,44,Sim,Casado,Masculino,Ravi Silva,Medicamentos,Tecnico de TI,1.0,2,Medicina,2326,Nao,20,6,3
1080,1160,31,Sim,Casado,Masculino,Ravi Oliveira,Saude,Tecnico de Laboratorio,15.0,3,Medicina,6233,Nao,2,2,2
1140,1309,32,Sim,Casado,Masculino,Heitor Dias,Saude,Tecnico de Laboratorio,7.0,2,Ciencias Sociais,22845,Nao,10,4,1
1146,1333,44,Sim,Casado,Masculino,Valentin Martins,Saude,Tecnico de Laboratorio,3.0,3,Ciencias Sociais,14669,Nao,3,2,1
1163,1389,31,Sim,Casado,Masculino,Lorenzo Barros,Saude,Diretor de Manufatura,22.0,4,Medicina,21057,Sim,10,2,6
1190,1464,31,Sim,Casado,Masculino,Ravi Rodrigues,Saude,Tecnico de Laboratorio,2.0,3,Ciencias Sociais,21081,Sim,2,2,2
1241,1562,30,Sim,Casado,Masculino,Gabriel Oliveira,Alimentos,Auditor,1.0,3,Ciencias Sociais,5323,Nao,10,8,6
1245,1573,38,Sim,Casado,Masculino,Miguel Teixeira,Saude,Diretor de Manufatura,2.0,3,Medicina,7653,Nao,5,2,1
1275,1639,35,Sim,Casado,Masculino,Henrique Ferreira,Alimentos,Auditor,10.0,3,Medicina,21530,Nao,13,12,6
1312,1716,47,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,9.0,3,Ciencias Sociais,24164,Nao,23,5,14
1333,1761,31,Sim,Casado,Masculino,Miguel Martins,Alimentos,Auditor,16.0,4,Marketing,19002,Nao,1,0,0
1337,1767,43,Sim,Casado,Masculino,Ravi Santos,Saude,Pesquisador,17.0,3,Formacao Tecnica,15587,Sim,1,0,0
1358,1807,34,Sim,Casado,Masculino,Caio Mendes,Saude,Tecnico de Laboratorio,9.0,4,Ciencias Sociais,6208,Nao,7,1,0
1368,1842,31,Sim,Casado,Masculino,Ravi Rodrigues,Medicamentos,Tecnico de TI,18.0,5,Recursos Humanos,21495,Nao,1,0,0
1393,1905,34,Sim,Casado,Masculino,Gabriel Oliveira,Saude,Pesquisador,16.0,4,Formacao Tecnica,14460,Sim,5,2,3
1422,1967,31,Sim,Casado,Masculino,Pedro Santos,Alimentos,Auditor,26.0,4,Marketing,21075,Sim,10,7,0
1455,2032,56,Sim,Casado,Masculino,Pedro Barros,Saude,Tecnico de Laboratorio,7.0,2,Formacao Tecnica,3666,Nao,10,9,9

In [12]:
# OpÃ§Ã£o 1 - cria o objeto base filtrada
base_filtrada= base[
    (base['IDADE']>=30)&
    (base['STATUSCIVIL']=='Casado')&
    (base['INSATISTFEITO']=="Sim")
    ]

In [13]:
#OpÃ§Ã£o 2 - Ja cria o subseting diretamente das colunas que preciso
base_filtrada_sub= base[
    (base['IDADE']>=30)&
    (base['STATUSCIVIL']=='Casado')&
    (base['INSATISTFEITO']=="Sim")
    ][['IDADE','STATUSCIVIL']]

In [14]:
base_filtrada

,IDCOLABORADOR,IDADE,INSATISTFEITO,STATUSCIVIL,GENERO,NOME,SETOR,CARGO,CEP,NIVELEDUCACAO,FORMACAO,RENDAMENSAL,DESCONTOULTIMAFATURA,ANONAEMPRESA,ANOSMESMAPOSICAO,ANOSDESDEULTIMAPROMOCAO
18,58,41,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Pesquisa,12.0,3,Formacao Tecnica,16280,Nao,22,15,15
46,161,56,Sim,Casado,Feminino,Vanessa Carvalho,Saude,Pesquisador,14.0,4,Ciencias Sociais,4510,Sim,5,4,4
48,165,58,Sim,Casado,Feminino,Amanda Goncalves,Saude,Representante da Saude,23.0,4,Medicina,3465,Nao,40,10,15
52,175,31,Sim,Casado,Feminino,Ana Pereira,Alimentos,Auditor,20.0,3,Ciencias Sociais,24788,Sim,2,2,2
96,328,33,Sim,Casado,Feminino,Patricia Oliveira,Saude,Tecnico de Laboratorio,2.0,2,Ciencias Sociais,21509,Nao,9,7,1
126,445,39,Sim,Casado,Feminino,Tatiane Carvalho,Alimentos,Auditor,3.0,2,Medicina,17778,Sim,1,0,0
203,684,45,Sim,Casado,Feminino,Fernanda Costa,Alimentos,Auditor,26.0,4,Ciencias Sociais,5630,Nao,1,1,0
247,840,49,Sim,Casado,Feminino,Bruna Almeida,Alimentos,Auditor,11.0,3,Marketing,5860,Nao,9,8,7
294,1004,30,Sim,Casado,Feminino,Laura Pereira,Saude,Pesquisador,22.0,3,Ciencias Sociais,11539,Sim,5,2,0
306,1033,37,Sim,Casado,Feminino,Leticia Oliveira,Saude,Representante da Saude,11.0,2,Medicina,14382,Nao,1,0,0
308,1038,52,Sim,Casado,Feminino,Valentina Martins,Alimentos,Gestor,2.0,1,Marketing,25846,Nao,32,14,6
380,1295,44,Sim,Casado,Feminino,Fernanda Alves,Saude,Representante da Saude,15.0,3,Medicina,14075,Nao,10,7,0
399,1360,58,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Manufatura,7.0,4,Medicina,12023,Sim,10,9,5
408,1380,35,Sim,Casado,Feminino,Daniela Silva,Alimentos,Auditor,18.0,4,Marketing,23288,Sim,4,2,3
434,1467,34,Sim,Casado,Feminino,Luana Almeida,Medicamentos,Tecnico de TI,9.0,4,Formacao Tecnica,3072,Nao,2,2,2
454,1572,53,Sim,Casado,Feminino,Rafaela Santos,Saude,Diretor de Manufatura,2.0,5,Formacao Tecnica,14618,Nao,33,7,1
494,1691,48,Sim,Casado,Feminino,Michele Almeida,Alimentos,Representante de Setor,7.0,2,Medicina,11740,Sim,9,7,7
523,1821,46,Sim,Casado,Feminino,Luana Oliveira,Saude,Representante da Saude,21.0,2,Medicina,10842,Nao,9,7,3
539,1869,46,Sim,Casado,Feminino,Priscila Pereira,Alimentos,Auditor,10.0,3,Ciencias Sociais,14011,Nao,8,7,0
609,42,39,Sim,Casado,Masculino,Anselmo Souza,Alimentos,Representante de Setor,NaN,3,Formacao Tecnica,3335,Nao,1,0,0
611,47,50,Sim,Casado,Masculino,AntÃ´nio Oliveira,Alimentos,Representante de Setor,3.0,2,Marketing,3810,Sim,3,2,0
629,90,36,Sim,Casado,Masculino,Cicero Dias,Saude,Pesquisador,9.0,3,Medicina,21777,Sim,1,0,0
665,163,31,Sim,Casado,Masculino,Genaro Rodrigues,Alimentos,Auditor,6.0,4,Ciencias Sociais,20739,Sim,7,7,7
700,261,35,Sim,Casado,Masculino,Marinheiro Dias,Saude,Diretor de Manufatura,23.0,2,Ciencias Sociais,15497,Sim,1,0,0
710,282,38,Sim,Casado,Masculino,Nathan Nunes,Saude,Representante da Saude,29.0,1,Medicina,11354,Sim,1,0,0
714,291,32,Sim,Casado,Masculino,Olavo Costa,Alimentos,Auditor,4.0,4,Medicina,25812,Nao,14,8,9
727,325,33,Sim,Casado,Masculino,Ranieri Nunes,Saude,Tecnico de Laboratorio,14.0,3,Medicina,22149,Sim,5,4,0
753,376,47,Sim,Casado,Masculino,Victor Barros,Saude,Gestor,29.0,4,Ciencias Sociais,10268,Sim,10,7,9
784,433,52,Sim,Casado,Masculino,Bernardo Jose Ferreira,Saude,Pesquisador,8.0,4,Medicina,17747,Nao,8,2,7
812,492,40,Sim,Casado,Masculino,Edmilson Costa,Alimentos,Auditor,22.0,2,Marketing,6110,Sim,6,4,1
845,582,33,Sim,Casado,Masculino,Joaquim Nunes,Saude,Gestor,15.0,1,Medicina,24619,Sim,7,6,7
849,587,31,Sim,Casado,Masculino,Jose Roberto Barros,Saude,Representante da Saude,20.0,3,Ciencias Sociais,22908,Nao,1,0,0
867,631,32,Sim,Casado,Masculino,Enzo Nunes,Alimentos,Auditor,11.0,4,Outros,23914,Nao,4,2,1
875,648,30,Sim,Casado,Masculino,Gael Rodrigues,Alimentos,Representante de Setor,12.0,4,Ciencias Sociais,14470,Nao,1,0,0
905,723,50,Sim,Casado,Masculino,Gael Rodrigues,Alimentos,Auditor,8.0,2,Formacao Tecnica,23452,Sim,4,3,1
930,787,55,Sim,Casado,Masculino,Gael Barros,Saude,Gestor,2.0,3,Medicina,21199,Sim,5,2,1
984,932,39,Sim,Casado,Masculino,Gael Nunes,Saude,Tecnico de Laboratorio,6.0,3,Medicina,4303,Sim,2,2,2
998,967,36,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,3.0,1,Ciencias Sociais,5518,Sim,16,7,3
999,970,37,Sim,Casado,Masculino,Otavio Dias,Alimentos,Auditor,1.0,4,Ciencias Sociais,14922,Nao,14,1,11
1041,1081,51,Sim,Casado,Masculino,Miguel Martins,Saude,Pesquisador,4.0,4,Ciencias Sociais,10332,Sim,10,0,2
1048,1098,44,Sim,Casado,Masculino,Ravi Silva,Medicamentos,Tecnico de TI,1.0,2,Medicina,2326,Nao,20,6,3
1080,1160,31,Sim,Casado,Masculino,Ravi Oliveira,Saude,Tecnico de Laboratorio,15.0,3,Medicina,6233,Nao,2,2,2
1140,1309,32,Sim,Casado,Masculino,Heitor Dias,Saude,Tecnico de Laboratorio,7.0,2,Ciencias Sociais,22845,Nao,10,4,1
1146,1333,44,Sim,Casado,Masculino,Valentin Martins,Saude,Tecnico de Laboratorio,3.0,3,Ciencias Sociais,14669,Nao,3,2,1
1163,1389,31,Sim,Casado,Masculino,Lorenzo Barros,Saude,Diretor de Manufatura,22.0,4,Medicina,21057,Sim,10,2,6
1190,1464,31,Sim,Casado,Masculino,Ravi Rodrigues,Saude,Tecnico de Laboratorio,2.0,3,Ciencias Sociais,21081,Sim,2,2,2
1241,1562,30,Sim,Casado,Masculino,Gabriel Oliveira,Alimentos,Auditor,1.0,3,Ciencias Sociais,5323,Nao,10,8,6
1245,1573,38,Sim,Casado,Masculino,Miguel Teixeira,Saude,Diretor de Manufatura,2.0,3,Medicina,7653,Nao,5,2,1
1275,1639,35,Sim,Casado,Masculino,Henrique Ferreira,Alimentos,Auditor,10.0,3,Medicina,21530,Nao,13,12,6
1312,1716,47,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,9.0,3,Ciencias Sociais,24164,Nao,23,5,14
1333,1761,31,Sim,Casado,Masculino,Miguel Martins,Alimentos,Auditor,16.0,4,Marketing,19002,Nao,1,0,0
1337,1767,43,Sim,Casado,Masculino,Ravi Santos,Saude,Pesquisador,17.0,3,Formacao Tecnica,15587,Sim,1,0,0
1358,1807,34,Sim,Casado,Masculino,Caio Mendes,Saude,Tecnico de Laboratorio,9.0,4,Ciencias Sociais,6208,Nao,7,1,0
1368,1842,31,Sim,Casado,Masculino,Ravi Rodrigues,Medicamentos,Tecnico de TI,18.0,5,Recursos Humanos,21495,Nao,1,0,0
1393,1905,34,Sim,Casado,Masculino,Gabriel Oliveira,Saude,Pesquisador,16.0,4,Formacao Tecnica,14460,Sim,5,2,3
1422,1967,31,Sim,Casado,Masculino,Pedro Santos,Alimentos,Auditor,26.0,4,Marketing,21075,Sim,10,7,0
1455,2032,56,Sim,Casado,Masculino,Pedro Barros,Saude,Tecnico de Laboratorio,7.0,2,Formacao Tecnica,3666,Nao,10,9,9

In [15]:
base_filtrada_sub

      IDADE STATUSCIVIL
18       41      Casado
46       56      Casado
48       58      Casado
52       31      Casado
96       33      Casado
126      39      Casado
203      45      Casado
247      49      Casado
294      30      Casado
306      37      Casado
308      52      Casado
380      44      Casado
399      58      Casado
408      35      Casado
434      34      Casado
454      53      Casado
494      48      Casado
523      46      Casado
539      46      Casado
609      39      Casado
611      50      Casado
629      36      Casado
665      31      Casado
700      35      Casado
710      38      Casado
714      32      Casado
727      33      Casado
753      47      Casado
784      52      Casado
812      40      Casado
845      33      Casado
849      31      Casado
867      32      Casado
875      30      Casado
905      50      Casado
930      55      Casado
984      39      Casado
998      36      Casado
999      37      Casado
1041     51      Casado
1048     44      Casado
1080     31      Casado
1140     32      Casado
1146     44      Casado
1163     31      Casado
1190     31      Casado
1241     30      Casado
1245     38      Casado
1275     35      Casado
1312     47      Casado
1333     31      Casado
1337     43      Casado
1358     34      Casado
1368     31      Casado
1393     34      Casado
1422     31      Casado
1455     56      Casado

ApÃ³s criar a base filtrada podemos deletar a base original para reduzir o tamabho do arquivo - "del base"

Agora vamos exportar para csv

In [16]:
base_filtrada.to_csv('base_filtrada.csv',index=False, decimal=',')

Incluindo colunas

In [17]:
base_filtrada['Coluna_nova'] = base_filtrada['IDADE'] + 10

C:\Users\jonat\AppData\Local\Temp\ipykernel_14512\347492228.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_filtrada['Coluna_nova'] = base_filtrada['IDADE'] + 10

In [18]:
base_filtrada

,IDCOLABORADOR,IDADE,INSATISTFEITO,STATUSCIVIL,GENERO,NOME,SETOR,CARGO,CEP,NIVELEDUCACAO,FORMACAO,RENDAMENSAL,DESCONTOULTIMAFATURA,ANONAEMPRESA,ANOSMESMAPOSICAO,ANOSDESDEULTIMAPROMOCAO,Coluna_nova
18,58,41,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Pesquisa,12.0,3,Formacao Tecnica,16280,Nao,22,15,15,51
46,161,56,Sim,Casado,Feminino,Vanessa Carvalho,Saude,Pesquisador,14.0,4,Ciencias Sociais,4510,Sim,5,4,4,66
48,165,58,Sim,Casado,Feminino,Amanda Goncalves,Saude,Representante da Saude,23.0,4,Medicina,3465,Nao,40,10,15,68
52,175,31,Sim,Casado,Feminino,Ana Pereira,Alimentos,Auditor,20.0,3,Ciencias Sociais,24788,Sim,2,2,2,41
96,328,33,Sim,Casado,Feminino,Patricia Oliveira,Saude,Tecnico de Laboratorio,2.0,2,Ciencias Sociais,21509,Nao,9,7,1,43
126,445,39,Sim,Casado,Feminino,Tatiane Carvalho,Alimentos,Auditor,3.0,2,Medicina,17778,Sim,1,0,0,49
203,684,45,Sim,Casado,Feminino,Fernanda Costa,Alimentos,Auditor,26.0,4,Ciencias Sociais,5630,Nao,1,1,0,55
247,840,49,Sim,Casado,Feminino,Bruna Almeida,Alimentos,Auditor,11.0,3,Marketing,5860,Nao,9,8,7,59
294,1004,30,Sim,Casado,Feminino,Laura Pereira,Saude,Pesquisador,22.0,3,Ciencias Sociais,11539,Sim,5,2,0,40
306,1033,37,Sim,Casado,Feminino,Leticia Oliveira,Saude,Representante da Saude,11.0,2,Medicina,14382,Nao,1,0,0,47
308,1038,52,Sim,Casado,Feminino,Valentina Martins,Alimentos,Gestor,2.0,1,Marketing,25846,Nao,32,14,6,62
380,1295,44,Sim,Casado,Feminino,Fernanda Alves,Saude,Representante da Saude,15.0,3,Medicina,14075,Nao,10,7,0,54
399,1360,58,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Manufatura,7.0,4,Medicina,12023,Sim,10,9,5,68
408,1380,35,Sim,Casado,Feminino,Daniela Silva,Alimentos,Auditor,18.0,4,Marketing,23288,Sim,4,2,3,45
434,1467,34,Sim,Casado,Feminino,Luana Almeida,Medicamentos,Tecnico de TI,9.0,4,Formacao Tecnica,3072,Nao,2,2,2,44
454,1572,53,Sim,Casado,Feminino,Rafaela Santos,Saude,Diretor de Manufatura,2.0,5,Formacao Tecnica,14618,Nao,33,7,1,63
494,1691,48,Sim,Casado,Feminino,Michele Almeida,Alimentos,Representante de Setor,7.0,2,Medicina,11740,Sim,9,7,7,58
523,1821,46,Sim,Casado,Feminino,Luana Oliveira,Saude,Representante da Saude,21.0,2,Medicina,10842,Nao,9,7,3,56
539,1869,46,Sim,Casado,Feminino,Priscila Pereira,Alimentos,Auditor,10.0,3,Ciencias Sociais,14011,Nao,8,7,0,56
609,42,39,Sim,Casado,Masculino,Anselmo Souza,Alimentos,Representante de Setor,NaN,3,Formacao Tecnica,3335,Nao,1,0,0,49
611,47,50,Sim,Casado,Masculino,AntÃ´nio Oliveira,Alimentos,Representante de Setor,3.0,2,Marketing,3810,Sim,3,2,0,60
629,90,36,Sim,Casado,Masculino,Cicero Dias,Saude,Pesquisador,9.0,3,Medicina,21777,Sim,1,0,0,46
665,163,31,Sim,Casado,Masculino,Genaro Rodrigues,Alimentos,Auditor,6.0,4,Ciencias Sociais,20739,Sim,7,7,7,41
700,261,35,Sim,Casado,Masculino,Marinheiro Dias,Saude,Diretor de Manufatura,23.0,2,Ciencias Sociais,15497,Sim,1,0,0,45
710,282,38,Sim,Casado,Masculino,Nathan Nunes,Saude,Representante da Saude,29.0,1,Medicina,11354,Sim,1,0,0,48
714,291,32,Sim,Casado,Masculino,Olavo Costa,Alimentos,Auditor,4.0,4,Medicina,25812,Nao,14,8,9,42
727,325,33,Sim,Casado,Masculino,Ranieri Nunes,Saude,Tecnico de Laboratorio,14.0,3,Medicina,22149,Sim,5,4,0,43
753,376,47,Sim,Casado,Masculino,Victor Barros,Saude,Gestor,29.0,4,Ciencias Sociais,10268,Sim,10,7,9,57
784,433,52,Sim,Casado,Masculino,Bernardo Jose Ferreira,Saude,Pesquisador,8.0,4,Medicina,17747,Nao,8,2,7,62
812,492,40,Sim,Casado,Masculino,Edmilson Costa,Alimentos,Auditor,22.0,2,Marketing,6110,Sim,6,4,1,50
845,582,33,Sim,Casado,Masculino,Joaquim Nunes,Saude,Gestor,15.0,1,Medicina,24619,Sim,7,6,7,43
849,587,31,Sim,Casado,Masculino,Jose Roberto Barros,Saude,Representante da Saude,20.0,3,Ciencias Sociais,22908,Nao,1,0,0,41
867,631,32,Sim,Casado,Masculino,Enzo Nunes,Alimentos,Auditor,11.0,4,Outros,23914,Nao,4,2,1,42
875,648,30,Sim,Casado,Masculino,Gael Rodrigues,Alimentos,Representante de Setor,12.0,4,Ciencias Sociais,14470,Nao,1,0,0,40
905,723,50,Sim,Casado,Masculino,Gael Rodrigues,Alimentos,Auditor,8.0,2,Formacao Tecnica,23452,Sim,4,3,1,60
930,787,55,Sim,Casado,Masculino,Gael Barros,Saude,Gestor,2.0,3,Medicina,21199,Sim,5,2,1,65
984,932,39,Sim,Casado,Masculino,Gael Nunes,Saude,Tecnico de Laboratorio,6.0,3,Medicina,4303,Sim,2,2,2,49
998,967,36,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,3.0,1,Ciencias Sociais,5518,Sim,16,7,3,46
999,970,37,Sim,Casado,Masculino,Otavio Dias,Alimentos,Auditor,1.0,4,Ciencias Sociais,14922,Nao,14,1,11,47
1041,1081,51,Sim,Casado,Masculino,Miguel Martins,Saude,Pesquisador,4.0,4,Ciencias Sociais,10332,Sim,10,0,2,61
1048,1098,44,Sim,Casado,Masculino,Ravi Silva,Medicamentos,Tecnico de TI,1.0,2,Medicina,2326,Nao,20,6,3,54
1080,1160,31,Sim,Casado,Masculino,Ravi Oliveira,Saude,Tecnico de Laboratorio,15.0,3,Medicina,6233,Nao,2,2,2,41
1140,1309,32,Sim,Casado,Masculino,Heitor Dias,Saude,Tecnico de Laboratorio,7.0,2,Ciencias Sociais,22845,Nao,10,4,1,42
1146,1333,44,Sim,Casado,Masculino,Valentin Martins,Saude,Tecnico de Laboratorio,3.0,3,Ciencias Sociais,14669,Nao,3,2,1,54
1163,1389,31,Sim,Casado,Masculino,Lorenzo Barros,Saude,Diretor de Manufatura,22.0,4,Medicina,21057,Sim,10,2,6,41
1190,1464,31,Sim,Casado,Masculino,Ravi Rodrigues,Saude,Tecnico de Laboratorio,2.0,3,Ciencias Sociais,21081,Sim,2,2,2,41
1241,1562,30,Sim,Casado,Masculino,Gabriel Oliveira,Alimentos,Auditor,1.0,3,Ciencias Sociais,5323,Nao,10,8,6,40
1245,1573,38,Sim,Casado,Masculino,Miguel Teixeira,Saude,Diretor de Manufatura,2.0,3,Medicina,7653,Nao,5,2,1,48
1275,1639,35,Sim,Casado,Masculino,Henrique Ferreira,Alimentos,Auditor,10.0,3,Medicina,21530,Nao,13,12,6,45
1312,1716,47,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,9.0,3,Ciencias Sociais,24164,Nao,23,5,14,57
1333,1761,31,Sim,Casado,Masculino,Miguel Martins,Alimentos,Auditor,16.0,4,Marketing,19002,Nao,1,0,0,41
1337,1767,43,Sim,Casado,Masculino,Ravi Santos,Saude,Pesquisador,17.0,3,Formacao Tecnica,15587,Sim,1,0,0,53
1358,1807,34,Sim,Casado,Masculino,Caio Mendes,Saude,Tecnico de Laboratorio,9.0,4,Ciencias Sociais,6208,Nao,7,1,0,44
1368,1842,31,Sim,Casado,Masculino,Ravi Rodrigues,Medicamentos,Tecnico de TI,18.0,5,Recursos Humanos,21495,Nao,1,0,0,41
1393,1905,34,Sim,Casado,Masculino,Gabriel Oliveira,Saude,Pesquisador,16.0,4,Formacao Tecnica,14460,Sim,5,2,3,44
1422,1967,31,Sim,Casado,Masculino,Pedro Santos,Alimentos,Auditor,26.0,4,Marketing,21075,Sim,10,7,0,41
1455,2032,56,Sim,Casado,Masculino,Pedro Barros,Saude,Tecnico de Laboratorio,7.0,2,Formacao Tecnica,3666,Nao,10,9,9,66

# Aula do dia 31/01/2025

In [48]:
energia = pd.read_csv(r"C:\Users\jonat\OneDrive\Documentos\GitHub\Curso-CDIA\previsao_energia_solar (1).csv", decimal=',')

In [49]:
energia

,Localizacao,Data,Mes,Hora,Estacao,Umidade,Temperatura,Geracao,Vento,Visibilidade,Pressao,Cloud.Ceiling
0,0,20171203,12,11,0,81.71997,12.86919,2.42769,5,10.0,1010.6,722
1,0,20171203,12,13,0,96.64917,9.66415,2.46273,0,10.0,1011.3,23
2,0,20171203,12,13,0,93.61572,15.44983,4.46836,5,10.0,1011.6,32
3,0,20171204,12,12,0,77.21558,10.36659,1.65364,5,2.0,1024.4,6
4,0,20171204,12,14,0,54.80347,16.85471,6.57939,3,3.0,1023.7,9
...,...,...,...,...,...,...,...,...,...,...,...,...
21040,11,20180928,9,15,3,11.66992,43.22510,9.79611,14,10.0,802.3,722
21041,11,20180929,9,13,3,18.22510,28.98247,10.88992,13,10.0,799.2,722
21042,11,20180929,9,14,3,15.52124,33.49167,8.24479,10,10.0,798.4,722
21043,11,20180929,9,15,3,6.63452,51.62163,12.47328,10,10.0,797.8,722
21044,11,20181001,10,14,3,22.58301,32.83958,6.39732,15,10.0,801.2,110

In [50]:
energia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21045 entries, 0 to 21044
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Localizacao    21045 non-null  int64
 1   Data           21045 non-null  int64
 2   Mes            21045 non-null  int64
 3   Hora           21045 non-null  int64
 4   Estacao        21045 non-null  int64
 5   Umidade        21045 non-null  float64
 6   Temperatura    21045 non-null  float64
 7   Geracao        21045 non-null  float64
 8   Vento          21045 non-null  int64
 9   Visibilidade   21045 non-null  float64
 10  Pressao        21045 non-null  float64
 11  Cloud.Ceiling  21045 non-null  int64
dtypes: float64(5), int64(7)
memory usage: 1.9 MB

In [22]:
energia.describe()

,Localizacao,Data,Mes,Hora,Estacao,Vento,Cloud.Ceiling
count,21045.000000,2.104500e+04,21045.000000,21045.000000,21045.000000,21045.000000,21045.000000
mean,6.091518,2.017720e+07,6.565883,12.627845,1.636731,10.318318,515.966785
std,3.600643,4.579585e+03,2.983958,1.672952,0.997188,6.385030,301.903379
min,0.000000,2.017052e+07,1.000000,10.000000,0.000000,0.000000,0.000000
25%,3.000000,2.017111e+07,4.000000,11.000000,1.000000,6.000000,140.000000
50%,6.000000,2.018032e+07,7.000000,13.000000,2.000000,9.000000,722.000000
75%,10.000000,2.018062e+07,9.000000,14.000000,2.000000,14.000000,722.000000
max,11.000000,2.018100e+07,12.000000,15.000000,3.000000,49.000000,722.000000

## Iniciando o SKLEARN para fazer o train test split

In [52]:
from sklearn.model_selection import train_test_split

### Cirando a as varÃ¡veis X e Y - sendo X a a base sem a variÃ¡vel alvo e o Y apenas a variÃ¡vel alvo

In [53]:
X = energia.drop('Geracao', axis=1)
y = energia['Geracao']

In [54]:
X

,Localizacao,Data,Mes,Hora,Estacao,Umidade,Temperatura,Vento,Visibilidade,Pressao,Cloud.Ceiling
0,0,20171203,12,11,0,81.71997,12.86919,5,10.0,1010.6,722
1,0,20171203,12,13,0,96.64917,9.66415,0,10.0,1011.3,23
2,0,20171203,12,13,0,93.61572,15.44983,5,10.0,1011.6,32
3,0,20171204,12,12,0,77.21558,10.36659,5,2.0,1024.4,6
4,0,20171204,12,14,0,54.80347,16.85471,3,3.0,1023.7,9
...,...,...,...,...,...,...,...,...,...,...,...
21040,11,20180928,9,15,3,11.66992,43.22510,14,10.0,802.3,722
21041,11,20180929,9,13,3,18.22510,28.98247,13,10.0,799.2,722
21042,11,20180929,9,14,3,15.52124,33.49167,10,10.0,798.4,722
21043,11,20180929,9,15,3,6.63452,51.62163,10,10.0,797.8,722
21044,11,20181001,10,14,3,22.58301,32.83958,15,10.0,801.2,110

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [64]:
[X_train.shape, X_test.shape, y_train.shape, y_test.shape]

[(14731, 11), (6314, 11), (14731,), (6314,)]

### Agora vamos importar o modelo que treinaremos com os dados

In [56]:
from sklearn.linear_model import LinearRegression

In [57]:
modelo = LinearRegression()

In [58]:
modelo.fit(X_train, y_train)

LinearRegression()

In [71]:
y_pred = modelo.predict(X_test)

In [65]:
modelo.score(X_test, y_test)

0.4650574337580161

### Aqui ele da o coeficiente de correlaÃ§Ã£o de cada uam das 11 variÃ¡veis independentes

In [70]:
modelo.coef_

array([-1.15226097e-01, -6.88007778e-05, -4.87036591e-01, -9.25196127e-02,
        3.85676781e-01, -3.39978232e-02,  2.82905979e-01,  1.27104909e-01,
        1.36818858e-01,  1.30985478e-02,  4.93658195e-03])

### Incluir as previsÃµes e valores reais na tabela X_test para verificar a acuracia

In [72]:
X_test['y_pred'] = y_pred
X_test['y_test'] = y_test

In [73]:
X_test

,Localizacao,Data,Mes,Hora,Estacao,Umidade,Temperatura,Vento,Visibilidade,Pressao,Cloud.Ceiling,y_pred,y_test
20644,11,20180727,7,11,2,35.69336,34.77318,7,10.0,805.6,24,9.438861,17.84274
20802,11,20180816,8,15,2,10.96802,58.63594,10,10.0,804.5,120,17.007966,15.79581
6836,4,20171115,11,13,3,71.70410,25.25124,18,10.0,1014.8,70,9.606600,11.40692
5865,3,20171122,11,13,3,36.25488,41.87813,3,10.0,1012.8,722,16.916268,23.09664
7628,4,20180531,5,14,1,53.44849,31.05705,21,10.0,1014.8,722,16.880234,22.65374
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2359,1,20180817,8,10,2,84.39941,26.43456,6,10.0,984.9,722,11.842666,9.51146
673,0,20180711,7,12,2,17.24243,43.85704,10,10.0,1011.3,722,20.333519,20.17488
12659,8,20180625,6,15,2,99.98779,23.30254,17,10.0,972.2,12,7.871559,0.75700
13138,9,20170630,6,15,2,22.19238,28.33542,7,10.0,816.2,160,9.928895,6.37840
15348,9,20180724,7,11,2,22.33276,46.36719,3,10.0,820.1,722,16.531009,16.52442